name: bankcard
favicon: null
layout_spectrum: 0.9701485806144774
typography_spectrum: 0.594820469385013
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3819123520515859
  lightness: 0.8480574334971607
  saturation: 0.5785604161210358
  rhythmicContrast: 0.12165084737353027
purpose: []
